### ISSUE TITLE
nginx template has a wrong config in proxy_backend.conf.template

### ISSUE THREAD

**Issue by sunyboy** [coreruleset/modsecurity-docker#150]
nginx template has a wrong config in proxy_backend.conf.template, you need to change "proxy_set_header Upgrade $connection_upgrade;" to "proxy_set_header Upgrade $http_upgrade;".Otherwise the websockets can not be used.
![Snipaste_2022-09-28_16-35-01](https://user-images.githubusercontent.com/9989854/192731071-66f4f165-bcb9-41d1-a1f3-e7c93580956f.png)

**Comment by theseion** [comment]
Thanks!

**Comment by fzipi** [comment]
@sunyboy are you sure that's the case?

We use it like this: https://github.com/coreruleset/modsecurity-docker/blob/ea97f48fdb98cf28a22d902a83839ec015ccdcaa/v3-nginx/templates/conf.d/default.conf.template#L3

**Comment by fzipi** [comment]
@sunyboy Did you check this one? ☝️

**Comment by fzipi** [comment]
No feedback from @sunyboy, closing.

**Comment by duhlin** [comment]
Hello,
I've noticed the same: impossible to establish a webocket with the default configuration.
Websocket can be established successfully with the suggested change, i.e. `proxy_set_header Upgrade $http_upgrade` instead of  `proxy_set_header Upgrade $connection_upgrade`.
The 'map' block in default.conf is the one suggested by http://nginx.org/en/docs/http/websocket.html.

**Comment by fzipi** [comment]
Ok, thanks for confirming. Will take a look then.

**Comment by theseion** [comment]
Yes, according to the docs, we accidentally use `$connection_upgrade` there: https://github.com/coreruleset/modsecurity-docker/blob/ea97f48fdb98cf28a22d902a83839ec015ccdcaa/v3-nginx/templates/includes/proxy_backend.conf.template#L3
