### ISSUE TITLE
Add letsencrypt

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [coreruleset/modsecurity-docker#69]
Please add Letsencrypt to Docker

**Comment by fzipi** [comment]
Hi @EvgenyPrikhodko !

Will include the same functionality in a next PR!

**Comment by fzipi** [comment]
@EvgenyPrikhodko I've used acme.sh in the past with reasonable success, which is a shell script ACME client. Has the same functionality than letsencrypt/certbot, but doesn't depend on python.

There are some problems depending on which web server we target. For apache, there is mod_md that solves mostly everything. I have a PR semi-baked, but still need some tests. For nginx, the problem is a bit different because there is no dynamic reloading of certificates.

We can do two things:
1) include the acme.sh binary in the dockers. You will need to run the update and restart nginx/apache in this case, certificates aren't going to be picked dynamically. We can use mod_md in apache, but that's one option.
2) https://github.com/acmesh-official/acme.sh/wiki/Run-acme.sh-in-docker

Even in 1) we have the problem of reloading nginx, or recreating basically what acme.sh has done already. What do you think? We can for sure simplify your task by including a new volume for certs, and point everything there so they are easy to regenerate.

**Comment by fzipi** [comment]
This is another approach that can be used for nginx: https://github.com/wmnnd/nginx-certbot

**Comment by fzipi** [comment]
Closing this one.
