### ISSUE TITLE
Change directory permissions for temporary files

### ISSUE THREAD

**Issue by fzipi** [coreruleset/modsecurity-docker#82]
Looking at debug error logs, found:
```
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client 172.25.0.1] ModSecurity: Multipart parsing error: Multipart: Failed to create file: /tmp/modsecurity/tmp/20210905-110250-YTSj2euvr-37s-pgdt6MeAAAAME-file-J0nssC [hostname "localhost"] [uri "/post"] [unique_id "YTSj2euvr-37s-pgdt6MeAAAAME"]
```

We need to add permissions to the `www-data` user, and we can just allow o+rwx on the `/tmp/modsecurity/tmp` directory, just in case.

**Comment by fzipi** [comment]
There is a workaround for this: use `MODSEC_TMP_DIR: "/tmp"`.

**Comment by harmenrenkema** [comment]
We ran into this issue when trying to upload a file through a modsecurity-crs nginx container. From the error log we got that modsecurity can't create a temporary file for processing the request body.

Turns out this is not because of permissions, but because the entire /tmp/modsecurity/{data,upload,tmp} directory structure doesn't exist in the container. 

Same goes for the apache variant.

**Comment by BFamzz** [comment]
> We ran into this issue when trying to upload a file through a modsecurity-crs nginx container. From the error log we got that modsecurity can't create a temporary file for processing the request body.
> 
> Turns out this is not because of permissions, but because the entire /tmp/modsecurity/{data,upload,tmp} directory structure doesn't exist in the container.
> 
> Same goes for the apache variant.

This issues still occurs. The directories are existent as shown below.

![image](https://user-images.githubusercontent.com/38426051/141387526-da547fab-b6ac-423e-bce8-358a52d48554.png)

@fzipi Please is there any fix for this?

Thanks.

**Comment by fzipi** [comment]
Ugh, taking a look, thanks.

**Comment by fzipi** [comment]
@BFamzz Can you add which version are you using?

**Comment by BFamzz** [comment]
Thanks for your response @fzipi 

The versions are as follows:

- Modsecurity: v3.0.5
- Modsecurity Connector: v1.0.2
- OWASP CRS: v3.3.2

This is shown in the screenshot below.

![image](https://user-images.githubusercontent.com/38426051/141431272-cc454c65-bb77-45b6-ab6e-f815813446ef.png)

**Comment by fzipi** [comment]
Excellent. I was just talking about which container you were pulling, but I can infer that from this data ;)

**Comment by fzipi** [comment]
@BFamzz I can't reproduce the problem in nginx-modsec3. But there is a permissions problem with the apache default container (I'm verifying the alpine one).

Can you paste here which version of the _container_ are you using? Is it the alpine version? Can you get me the image ID?

**Comment by BFamzz** [comment]
Hello @fzipi 

Container version: owasp/modsecurity-crs:3.3.2-nginx
Image ID: da8b2b5b5f1f

Please see the screenshot below:

![image](https://user-images.githubusercontent.com/38426051/141444149-275cd526-af6a-4b1c-a3df-d1ecf38a2ac8.png)

I will try and pull the image again. The most recent image is from 3 days ago. Mine is from 9 days ago.

I will update you shortly.

Thanks.

**Comment by BFamzz** [comment]
Hi @fzipi 

This is the new image ID

![image](https://user-images.githubusercontent.com/38426051/141445411-84948c9d-5aab-42d5-bdb4-7bfccee14fb3.png)

However, the issue is still occuring.

![image](https://user-images.githubusercontent.com/38426051/141446223-7b7fde3a-a771-428f-93d5-83f3544604d9.png)

Directory permission

![image](https://user-images.githubusercontent.com/38426051/141446311-f2a800e6-0c12-4374-907a-e3a373a236ee.png)

Image used by the running container

![image](https://user-images.githubusercontent.com/38426051/141446462-2a9a2642-d6c1-4f33-8308-4d7297b8b49e.png)

**Comment by fzipi** [comment]
Thanks, I could reproduce it now. Fixing.

**Comment by fzipi** [comment]
Just to have all the context: https://github.com/docker-library/httpd/issues/10. I think upstream is doing it wrong :/

**Comment by BFamzz** [comment]
Hi @fzipi 

Just to confirm, is the issue fixed in the recent most recent image (6 hours ago)

![image](https://user-images.githubusercontent.com/38426051/142046613-92ebcdef-5606-42b7-86db-e9b8c81b441c.png)

Thanks.

**Comment by fzipi360** [comment]
Hey @BFamzz ! The issue should be fixed for the base container, yes. The crs container will be building in top of that one.

**Comment by BFamzz** [comment]
Alright. Thanks.

**Comment by fzipi** [comment]
Just to document it here, upstream merged my fix so this should not be a problem anymore.
